# Generated by Django 2.1.3 on 2018-11-12 16:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_ck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='comment',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
